### PR TITLE
Feature(Service): add asynchronous feature

### PR DESCRIPTION
**Pull request by dobobaie**
Add asynchronous for handlers

### CODE REVIEW

**Comment by petersirka** [comment]
__Nice and thank you__. Currently I don't see any benefits of this change (can you create a better example of usage for me?) and I need to keep a backward compatibility to IE 10 and 11 because Tangular is used in web applications in most cases. For example there is no support for template literals (but this can be rewritten).

**Comment by dobobaie** [comment]
Oh I didn't see your compatibility to IE. In this case async/await is not possible. I'm using renderAsync for each asynchronous action. For example: 
```
Tangular.register("toBase64", async url => {
 // async code
 return base64Stream;
});
await Tangular.renderAsync("Hello <img src='{{ img | toBase64 }}'", { img: "http://myUrl.com/logo.png" });
```

**Comment by dobobaie** [comment]
I created a new package to keep Tangular compatible with IE => https://www.npmjs.com/package/tangular-async

**Comment by petersirka** [comment]
Great! :-)

**Comment by petersirka** [comment]
We can merge packages in the future.

**Comment by dobobaie** [comment]
Sure! Thank u for your package :)

**Pull request closed without merging**
